spring:
  datasource:
    url: jdbc:mysql://47.96.151.45:3306/weiqiann?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  #关闭引擎，模板的缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  #我们配置文件的真实位置
  messages:
    basename: i18n.login


#配置一个虚拟目录
server:
  servlet:
    context-path: /kuang

